name: OreLess
main: me.bitfreeze.OreLess.OreLess
version: 0.1
author: bitfreeze
description: Getting rid of ores from the main world, to encouraging players to use a mining world instead.
load: startup
commands:
    oreless:
        aliases: [ol]
        description: OreLess main command.
        usage: /<command> help
